<template>
  <div class="card">
    <div class="panel-header">
      <div>
        <div class="panel-title">Decision Feed</div>
        <div class="panel-subtitle">Latest structured outputs generated by the active strategy cycle.</div>
      </div>
      <span class="tag">{{ decisions.length }} records</span>
    </div>
    <div v-if="!decisions.length" class="empty-state">
      <strong>No decisions recorded yet</strong>
      <span class="muted">Run a strategy cycle or enable scheduled execution to populate this feed.</span>
    </div>
    <table v-else class="table">
      <thead>
        <tr>
          <th>Time</th>
          <th>Model</th>
          <th>Action</th>
          <th>Symbol</th>
          <th>Size</th>
          <th>Confidence</th>
          <th>Status</th>
          <th>Reason</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="decision in decisions" :key="decision.id">
          <td>{{ formatDateTime(decision.created_at) }}</td>
          <td>{{ decision.model_name || `Model #${decision.model_config_id}` }}</td>
          <td>
            <span class="status-pill" :class="actionClass(decision.action)">{{ decision.action }}</span>
          </td>
          <td>{{ decision.symbol || "-" }}</td>
          <td>{{ Number(decision.action === "BUY" ? decision.buy_pct : decision.sell_pct).toFixed(2) }}</td>
          <td>{{ Number(decision.confidence || 0).toFixed(2) }}</td>
          <td><span class="status-pill" :class="statusClass(decision.status)">{{ decision.status }}</span></td>
          <td>{{ decision.reason }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup>
import { formatDateTime } from "../utils/time";

defineProps({
  decisions: {
    type: Array,
    default: () => [],
  },
});

function actionClass(action) {
  if (action === "BUY") {
    return "success";
  }
  if (action === "SELL") {
    return "warning";
  }
  return "info";
}

function statusClass(status) {
  if (status === "accepted" || status === "completed") {
    return "success";
  }
  if (String(status).includes("fallback") || String(status).includes("failed")) {
    return "warning";
  }
  return "info";
}
</script>
